export type Store = {
  store_id: string;
  store_name: string;
  store_category: string;
  store_start_year: string;
  store_message: string;
  owner_name: string;
  short_summary: string;
  extended_summary: string;
  location: string;
  website: string;
  phone_number: string;
  email: string;
  facebook: string;
  instagram: string;
  twitter: string;
  prompt_1: string;
  prompt_answer_1: string;
  prompt_2: string;
  prompt_answer_2: string;
  prompt_3: string;
  prompt_answer_3: string;
  img_main: string;
  img_splash: string;
  img_1: string;
  img_2: string;
  img_3: string;
  img_profile: string;
  product_1_img: string;
  product_1_title: string;
  product_1_price: string;
  product_2_img: string;
  product_2_title: string;
  product_2_price: string;
  product_3_img: string;
  product_3_title: string;
  product_3_price: string;
};

export type IllustrationDataType = {
  img_url: string;
  timeframe: string;
  artist_name: string;
  artist_url: string;
};
