export type Store = {
  store_id: string;
  store_name: string;
  owner_name: string;
  short_summary: string;
  extended_summary: string;
  location: string;
  website: string;
  phone_number: string;
  facebook: string;
  instagram: string;
  twitter: string;
  prompt_1: string;
  prompt_answer_1: string;
  prompt_2: string;
  prompt_answer_2: string;
  prompt_3: string;
  prompt_answer_3: string;
  img_main: string;
};
